force-app/main/default/objects/Course__c/Course__c.object-meta.xml
<CustomObject>
    <label>Course</label>
    <nameField>
        <label>Course Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Courses</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

force-app/main/default/objects/Course__c/fields/Attendees_Count__c.field-meta.xml
<CustomField>
    <fullName>Attendees_Count__c</fullName>
    <description>The number of students currently enrolled in the course. This should
never exceed the Quota</description>
    <label>Attendees Count</label>
    <summaryForeignKey>Course_Participation__c.Course__c</summaryForeignKey>
    <summaryOperation>count</summaryOperation>
    <type>Summary</type>
</CustomField>

force-app/main/default/objects/Course__c/fields/Tutor__c.field-meta.xml
<CustomField>
    <fullName>Tutor__c</fullName>
    <deleteConstraint>Restrict</deleteConstraint>
    <description>Reference to the Tutor who will be leading the course. The records available for
the selection here should only be Person of type Tutor</description>
    <label>Tutor</label>
    <lookupFilter>
        <active>true</active>
        <filterItems>
            <field>Person__c.RecordTypeId</field>
            <operation>equals</operation>
            <value>Tutor</value>
        </filterItems>
        <isOptional>false</isOptional>
    </lookupFilter>
    <referenceTo>Person__c</referenceTo>
    <relationshipLabel>Courses</relationshipLabel>
    <relationshipName>Courses</relationshipName>
    <required>true</required>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/Person__c/Person__c.object-meta.xml
<CustomObject>
    <label>Person</label>
    <nameField>
        <label>Person Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Persons</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

force-app/main/default/classes/TutorsNotifier.cls
public with sharing class TutorsNotifier {

    public static boolean called = false;
    
    public static List<Messaging.SendEmailResult> findAndNotify(){
        
        List<Course__c> coursesWithoutAttendees = [SELECT Tutor__r.Email__c, Name  FROM Course__c WHERE Attendees_Count__c = 0 ORDER BY Tutor__r.Email__c];


            Map<String,List<String>> courseNamesByTutorEmail = new Map<String,List<String>>();

            for(Course__c course : coursesWithoutAttendees){
                if(courseNamesByTutorEmail.containsKey(course.Tutor__r.Email__c)){
                    courseNamesByTutorEmail.get(course.Tutor__r.Email__c).add(course.Name);
                }else{
                    courseNamesByTutorEmail.put(course.Tutor__r.Email__c, new List<String>{course.Name});
                }
            }

            List<Messaging.SingleEmailMessage> emailList = new List<Messaging.SingleEmailMessage>();

            for(String key : courseNamesByTutorEmail.keySet()){

                emailList.add(EmailService.createSingleEmailMessage(key, courseNamesByTutorEmail.get(key)));
                
            }

            called = true;

            return Messaging.sendEmail(emailList);

    }
}