force-app/main/default/objects/Number_Validation_API_Key__mdt/Number_Validation_API_Key__mdt.object-meta.xml
<CustomObject>
    <label>Number Validation API Key</label>
    <pluralLabel>Number Validation API Keys</pluralLabel>
</CustomObject>

force-app/main/default/objects/Number_Validation_API_Key__mdt/fields/Key__c.field-meta.xml
<CustomField>
    <fullName>Key__c</fullName>
    <defaultValue>&quot;PN34-MA87-EX28-WE53&quot;</defaultValue>
    <label>Key</label>
    <length>255</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/Person__c/Person__c.object-meta.xml
<CustomObject>
    <label>Person</label>
    <nameField>
        <label>Person Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Persons</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

force-app/main/default/objects/Phone_Validation_Result__c/Phone_Validation_Result__c.object-meta.xml
<CustomObject>
    <label>Phone Validation Result</label>
    <nameField>
        <label>Phone Validation Result Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Phone Validation Results</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

force-app/main/default/objects/Phone_Validation_Result__c/fields/Country_Prefix__c.field-meta.xml
<CustomField>
    <fullName>Country_Prefix__c</fullName>
    <description>The country prefix that must be prepended to the number when dialling internationally.</description>
    <label>Country Prefix</label>
    <precision>18</precision>
    <scale>0</scale>
    <type>Number</type>
</CustomField>

force-app/main/default/objects/Phone_Validation_Result__c/fields/Error_Cause__c.field-meta.xml
<CustomField>
    <fullName>Error_Cause__c</fullName>
    <label>Error Cause</label>
    <type>TextArea</type>
</CustomField>

force-app/main/default/objects/Phone_Validation_Result__c/fields/Error_Description__c.field-meta.xml
<CustomField>
    <fullName>Error_Description__c</fullName>
    <label>Error Description</label>
    <type>TextArea</type>
</CustomField>

force-app/main/default/objects/Phone_Validation_Result__c/fields/Error_Resolution__c.field-meta.xml
<CustomField>
    <fullName>Error_Resolution__c</fullName>
    <label>Error Resolution</label>
    <type>TextArea</type>
</CustomField>

force-app/main/default/objects/Phone_Validation_Result__c/fields/ErrorId__c.field-meta.xml
<CustomField>
    <fullName>ErrorId__c</fullName>
    <label>ErrorId</label>
    <precision>18</precision>
    <scale>0</scale>
    <type>Number</type>
</CustomField>

force-app/main/default/objects/Phone_Validation_Result__c/fields/Is_Valid__c.field-meta.xml
<CustomField>
    <fullName>Is_Valid__c</fullName>
    <description>Whether the number is valid or not (Maybe is returned if full validation couldn&apos;t be performed. Cellular network issues can cause temporary failures in the validation procedure). ([Yes|No|Maybe])</description>
    <label>Is Valid</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetDefinition>
            <value>
                <fullName>Maybe</fullName>
            </value>
            <value>
                <fullName>Yes</fullName>
            </value>
            <value>
                <fullName>No</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/objects/Phone_Validation_Result__c/fields/National_Format__c.field-meta.xml
<CustomField>
    <fullName>National_Format__c</fullName>
    <description>The domestic network format (useful for dialling from within the same country).</description>
    <label>National Format</label>
    <length>255</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/Phone_Validation_Result__c/fields/Network_Code__c.field-meta.xml
<CustomField>
    <fullName>Network_Code__c</fullName>
    <description>The current operator serving the supplied number.</description>
    <label>Network Code</label>
    <length>255</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/Phone_Validation_Result__c/fields/Network_Country__c.field-meta.xml
<CustomField>
    <fullName>Network_Country__c</fullName>
    <description>The country code of the operator.</description>
    <label>Network Country</label>
    <length>255</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/Phone_Validation_Result__c/fields/Network_Name__c.field-meta.xml
<CustomField>
    <fullName>Network_Name__c</fullName>
    <description>The name of the current operator serving the supplied number.</description>
    <label>Network Name</label>
    <length>255</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/Phone_Validation_Result__c/fields/Number_Type__c.field-meta.xml
<CustomField>
    <fullName>Number_Type__c</fullName>
    <description>The type of number that was detected in the request (MOBILE, LANDLINE OR VOIP).</description>
    <label>Number Type</label>
    <length>255</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/Phone_Validation_Result__c/fields/Person__c.field-meta.xml
<CustomField>
    <fullName>Person__c</fullName>
    <label>Person</label>
    <referenceTo>Person__c</referenceTo>
    <relationshipLabel>Phone Validation Results</relationshipLabel>
    <relationshipName>Phone_Validation_Results</relationshipName>
    <relationshipOrder>0</relationshipOrder>
    <type>MasterDetail</type>
</CustomField>

force-app/main/default/objects/Phone_Validation_Result__c/fields/Phone_Number__c.field-meta.xml
<CustomField>
    <fullName>Phone_Number__c</fullName>
    <description>The recipient phone number in international format.</description>
    <label>Phone Number</label>
    <length>255</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/Phone_Validation_Result__c/fields/Phone_Value__c.field-meta.xml
<CustomField>
    <fullName>Phone_Value__c</fullName>
    <label>Phone Value</label>
    <type>Phone</type>
</CustomField>

force-app/main/default/objects/Phone_Validation_Result__c/fields/Request_Processed__c.field-meta.xml
<CustomField>
    <fullName>Request_Processed__c</fullName>
    <defaultValue>false</defaultValue>
    <description>Returns true if we managed to process the request on the network or false if the validation attempt was unsuccessful.</description>
    <label>Request Processed</label>
    <type>Checkbox</type>
</CustomField>

force-app/main/default/objects/Phone_Validation_Result__c/fields/Validated_Field_Name__c.field-meta.xml
<CustomField>
    <fullName>Validated_Field_Name__c</fullName>
    <label>Validated Field Name</label>
    <length>255</length>
    <type>Text</type>
</CustomField>

force-app/main/default/classes/PhoneValidator.cls
public with sharing class PhoneValidator {

    @future (callout = true)
    public static void sendRequest(String personId){

        List<Person__c> persons = new List<Person__c>();

        if (Schema.sObjectType.Person__c.isAccessible()){
            persons = [SELECT Id, Name, Phone__c FROM Person__c WHERE Id = :personId];
        }


        if(!persons.isEmpty()){
            Person__c p = persons[0];

            Http http = new Http();
            HttpRequest request = new HttpRequest();

            String endpointUrl = p.Phone__c != null ? 'https://api.addressy.com/PhoneNumberValidation/Interactive/Validate/v2.20/json3.ws?Key=' + Number_Validation_API_Key__mdt.getInstance('Validation_Key').Key__c + '&Phone=' + p.Phone__c : 'https://api.addressy.com/PhoneNumberValidation/Interactive/Validate/v2.20/json3.ws?Key=' + Number_Validation_API_Key__mdt.getInstance('Validation_Key').Key__c;
        

            request.setEndpoint(endpointUrl);
            request.setMethod('GET');
            request.setHeader('Content-Type', 'application/json');
            request.setHeader('Accept','application/json');
            HttpResponse response = http.send(request);


            if(response.getStatusCode() == 200 && response != null){
                
                //create the Phone_Validation_Result__c object and populate appropriate fields;

                Phone_Validation_Result__c pvr = new Phone_Validation_Result__c(Name = p.Name + p.Phone__c, Validated_Field_Name__c = 'Phone__c', Phone_Value__c = p.Phone__c);
                pvr.Person__c = p.Id;

                JSON2Apex obj = JSON2Apex.parse(response.getBody());    

                if(obj.items[0].error != null){
                    //Populate Phone Validation Result with error related fields
                    pvr.ErrorId__c = obj.items[0].error;
                    pvr.Error_Description__c = obj.items[0].description;
                    pvr.Error_Cause__c = obj.items[0].cause;
                    pvr.Error_Resolution__c = obj.items[0].resolution;

                }else if(obj.items[0].phoneNumber != null){
                    //Populate Phone Validation Result with successfull call related fields
                    pvr.Phone_Number__c = obj.items[0].phoneNumber;
                    pvr.Request_Processed__c = obj.items[0].requestProcessed;
                    pvr.Is_Valid__c = obj.items[0].isValid;
                    pvr.Network_Code__c = obj.items[0].networkCode;
                    pvr.Network_Name__c = obj.items[0].networkName;
                    pvr.Network_Country__c = obj.items[0].networkCountry;
                    pvr.National_Format__c = obj.items[0].nationalFormat;
                    pvr.Country_Prefix__c = obj.items[0].countryPrefix;
                    pvr.Number_Type__c = obj.items[0].numberType;

                }

                //insert Phone Validation Result record

                if(Schema.sObjectType.Phone_Validation_Result__c.isCreateable()){
                    Database.insert(pvr, false);
                }

            }

            
   
        }
        
    }

}