force-app/main/default/objects/Number_Validation_API_Key__mdt/Number_Validation_API_Key__mdt.object-meta.xml
<CustomObject>
    <label>Number Validation API Key</label>
    <pluralLabel>Number Validation API Keys</pluralLabel>
</CustomObject>

force-app/main/default/objects/Number_Validation_API_Key__mdt/fields/Key__c.field-meta.xml
<CustomField>
    <fullName>Key__c</fullName>
    <defaultValue>&quot;PN34-MA87-EX28-WE53&quot;</defaultValue>
    <label>Key</label>
    <length>255</length>
    <type>Text</type>
</CustomField>

force-app/main/default/classes/CustomMetadataFetcherTest.cls
@isTest
public with sharing class CustomMetadataFetcherTest {
    @isTest
    static void getNumberValidationKey_shouldReturnValidKeyValue(){
        String expected = Number_Validation_API_Key__mdt.getInstance('Validation_Key').Key__c;
        Test.startTest();
        String actual = CustomMetadataFetcher.getNumberValidationKey();
        Test.stopTest();

        System.assertEquals(expected, actual);
    }
}