force-app/main/default/objects/Person__c/Person__c.object-meta.xml
<CustomObject>
    <label>Person</label>
    <nameField>
        <label>Person Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Persons</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

force-app/main/default/objects/Phone_Validation_Result__c/Phone_Validation_Result__c.object-meta.xml
<CustomObject>
    <label>Phone Validation Result</label>
    <nameField>
        <label>Phone Validation Result Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Phone Validation Results</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

force-app/main/default/objects/Phone_Validation_Result__c/fields/Country_Prefix__c.field-meta.xml
<CustomField>
    <fullName>Country_Prefix__c</fullName>
    <description>The country prefix that must be prepended to the number when dialling internationally.</description>
    <label>Country Prefix</label>
    <precision>18</precision>
    <scale>0</scale>
    <type>Number</type>
</CustomField>

force-app/main/default/objects/Phone_Validation_Result__c/fields/Error_Cause__c.field-meta.xml
<CustomField>
    <fullName>Error_Cause__c</fullName>
    <label>Error Cause</label>
    <type>TextArea</type>
</CustomField>

force-app/main/default/objects/Phone_Validation_Result__c/fields/Error_Description__c.field-meta.xml
<CustomField>
    <fullName>Error_Description__c</fullName>
    <label>Error Description</label>
    <type>TextArea</type>
</CustomField>

force-app/main/default/objects/Phone_Validation_Result__c/fields/Error_Resolution__c.field-meta.xml
<CustomField>
    <fullName>Error_Resolution__c</fullName>
    <label>Error Resolution</label>
    <type>TextArea</type>
</CustomField>

force-app/main/default/objects/Phone_Validation_Result__c/fields/ErrorId__c.field-meta.xml
<CustomField>
    <fullName>ErrorId__c</fullName>
    <label>ErrorId</label>
    <precision>18</precision>
    <scale>0</scale>
    <type>Number</type>
</CustomField>

force-app/main/default/objects/Phone_Validation_Result__c/fields/Is_Valid__c.field-meta.xml
<CustomField>
    <fullName>Is_Valid__c</fullName>
    <description>Whether the number is valid or not (Maybe is returned if full validation couldn&apos;t be performed. Cellular network issues can cause temporary failures in the validation procedure). ([Yes|No|Maybe])</description>
    <label>Is Valid</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetDefinition>
            <value>
                <fullName>Maybe</fullName>
            </value>
            <value>
                <fullName>Yes</fullName>
            </value>
            <value>
                <fullName>No</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/objects/Phone_Validation_Result__c/fields/National_Format__c.field-meta.xml
<CustomField>
    <fullName>National_Format__c</fullName>
    <description>The domestic network format (useful for dialling from within the same country).</description>
    <label>National Format</label>
    <length>255</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/Phone_Validation_Result__c/fields/Network_Code__c.field-meta.xml
<CustomField>
    <fullName>Network_Code__c</fullName>
    <description>The current operator serving the supplied number.</description>
    <label>Network Code</label>
    <length>255</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/Phone_Validation_Result__c/fields/Network_Country__c.field-meta.xml
<CustomField>
    <fullName>Network_Country__c</fullName>
    <description>The country code of the operator.</description>
    <label>Network Country</label>
    <length>255</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/Phone_Validation_Result__c/fields/Network_Name__c.field-meta.xml
<CustomField>
    <fullName>Network_Name__c</fullName>
    <description>The name of the current operator serving the supplied number.</description>
    <label>Network Name</label>
    <length>255</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/Phone_Validation_Result__c/fields/Number_Type__c.field-meta.xml
<CustomField>
    <fullName>Number_Type__c</fullName>
    <description>The type of number that was detected in the request (MOBILE, LANDLINE OR VOIP).</description>
    <label>Number Type</label>
    <length>255</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/Phone_Validation_Result__c/fields/Person__c.field-meta.xml
<CustomField>
    <fullName>Person__c</fullName>
    <label>Person</label>
    <referenceTo>Person__c</referenceTo>
    <relationshipLabel>Phone Validation Results</relationshipLabel>
    <relationshipName>Phone_Validation_Results</relationshipName>
    <relationshipOrder>0</relationshipOrder>
    <type>MasterDetail</type>
</CustomField>

force-app/main/default/objects/Phone_Validation_Result__c/fields/Phone_Number__c.field-meta.xml
<CustomField>
    <fullName>Phone_Number__c</fullName>
    <description>The recipient phone number in international format.</description>
    <label>Phone Number</label>
    <length>255</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/Phone_Validation_Result__c/fields/Request_Processed__c.field-meta.xml
<CustomField>
    <fullName>Request_Processed__c</fullName>
    <defaultValue>false</defaultValue>
    <description>Returns true if we managed to process the request on the network or false if the validation attempt was unsuccessful.</description>
    <label>Request Processed</label>
    <type>Checkbox</type>
</CustomField>

force-app/main/default/objects/Phone_Validation_Result__c/fields/Wrong_Response_Code_Body__c.field-meta.xml
<CustomField>
    <fullName>Wrong_Response_Code_Body__c</fullName>
    <label>Wrong Response Code Body</label>
    <length>100000</length>
    <type>LongTextArea</type>
</CustomField>

force-app/main/default/classes/TestPhoneValidator.cls
@isTest
public with sharing class TestPhoneValidator {
    
    @isTest
    static void sendRequest_SuccessfullValidationResultCreated_IfValidPhoneNumberProvided(){
        Test.setMock(HttpCalloutMock.class, new ResponseHttpCalloutMock('{"Items":[{"PhoneNumber":"+381645063016","RequestProcessed":true,"IsValid":"Yes","NetworkCode":"03","NetworkName":"Telekom Srbija ad Beograd (mts)","NetworkCountry":"RS","NationalFormat":"064 5063016","CountryPrefix":381,"NumberType":"Mobile"}]}', 200)); 


        Person__c person = new Person__c(Name = 'FirstName LastName', First_Name__c = 'FirstName', Last_Name__c = 'LastName', Email__c = 'cejicsasa17@gmail.com');
        person.Phone__c = '+381645063016';

        Test.startTest();

        insert person; 

        Test.stopTest();

        String personId = Id.valueOf(person.Id);

        List<Phone_Validation_Result__c> results = [SELECT Id, Phone_Number__c, Request_Processed__c, Is_Valid__c, Network_Code__c, Network_Name__c, Network_Country__c, National_Format__c, Country_Prefix__c, Number_Type__c  FROM Phone_Validation_Result__c WHERE Person__r.Id = :personId];

        Phone_Validation_Result__c pvr = results[results.size() - 1];

        System.assert(pvr != null);
        System.assertEquals('+381645063016', pvr.Phone_Number__c);
        System.assertEquals(True, pvr.Request_Processed__c);
        System.assertEquals('Yes', pvr.Is_Valid__c);
        System.assertEquals('03', pvr.Network_Code__c);
        System.assertEquals('Telekom Srbija ad Beograd (mts)', pvr.Network_Name__c);
        System.assertEquals('RS', pvr.Network_Country__c);
        System.assertEquals('064 5063016', pvr.National_Format__c);
        System.assertEquals(381, pvr.Country_Prefix__c);
        System.assertEquals('Mobile', pvr.Number_Type__c);
    }


    @isTest
    static void sendRequest_ErrorValidationResultCreated_IfNoPhoneNumberProvided(){
        
        Test.setMock(HttpCalloutMock.class, new ResponseHttpCalloutMock('{"Items":[{"Error":"1001","Description":"Number Required","Cause":"The phone numbers is required.","Resolution":"Please ensure that you supply a phone number and try again."}]}', 200)); 

        Person__c person = new Person__c(Name = 'FirstName LastName', First_Name__c = 'FirstName', Last_Name__c = 'LastName', Email__c = 'cejicsasa17@gmail.com');
        insert person; 

        Test.startTest();

        PhoneValidator.sendRequest(Id.valueOf(person.Id));

        Test.stopTest();

        String personId = Id.valueOf(person.Id);

        List<Phone_Validation_Result__c> results = [SELECT Id, ErrorId__c, Error_Description__c, Error_Cause__c, Error_Resolution__c  FROM Phone_Validation_Result__c WHERE Person__r.Id = :personId];

        Phone_Validation_Result__c pvr = results[results.size() - 1];

        System.assert(pvr != null);
        System.assertEquals(1001, pvr.ErrorId__c);
        System.assertEquals('Number Required', pvr.Error_Description__c);
        System.assertEquals('The phone numbers is required.', pvr.Error_Cause__c);
        System.assertEquals('Please ensure that you supply a phone number and try again.', pvr.Error_Resolution__c);
    }

    @isTest
    static void sendRequest_InvalidResponseCodeValidationResultCreated_IfNoCode200Returned(){
        Test.setMock(HttpCalloutMock.class, new ResponseHttpCalloutMock('invalid response code', 500)); 

        Test.startTest();

        Person__c person = new Person__c(Name = 'FirstName LastName', First_Name__c = 'FirstName', Last_Name__c = 'LastName', Email__c = 'cejicsasa17@gmail.com');
        insert person; 

        PhoneValidator.sendRequest(Id.valueOf(person.Id));

        Test.stopTest();

        String personId = Id.valueOf(person.Id);

        Phone_Validation_Result__c pvr = [SELECT Id, Wrong_Response_Code_Body__c  FROM Phone_Validation_Result__c WHERE Person__r.Id = :personId LIMIT 1];

        System.assertEquals('invalid response code', pvr.Wrong_Response_Code_Body__c);
    }


}